minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - next
  - "@next/*"
  - "@napi-rs/*"
  - "@unrs/*"
  - unrs-resolver
trustPolicy: no-downgrade

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
